project_name: extract
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0
    main: ./cmd/extract
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    format: binary
    replacements:
      darwin: mac
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
